version: '3'
services:
  kafka-zookeeper:
    image: spotify/kafka
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
      ADVERTISED_HOST: "localhost"
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"